name: Push to GitHub

on:
  push:
    branches:
      - origin/main 

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "ujalil929@gmail.com"
          git config user.name "ujalil101"

      - name: Push to GitHub
        run: |
          git add .
          git commit -m "Auto commit by GitHub Actions!!!"
          git push
